"""Initial migration

Revision ID: b0054716aebd
Revises: 
Create Date: 2024-09-30 23:19:32.023467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0054716aebd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('checkInTime', sa.String(length=5), nullable=True),
    sa.Column('exercised', sa.Boolean(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
